quarkus:
  http:
    port: 8081
    host: 0.0.0.0
  mongodb:
    connection-string: mongodb://127.0.0.1:27017/kitchensink?replicaSet=rs0&retryWrites=false
    database: kitchensink
  log:
    level: INFO