quarkus:
  http:
    port: 8081
    host: 0.0.0.0
  mongodb:
    connection-string: ${MONGODB_URI}
    database: kitchensink
    tls: true
    tls-insecure: true
  log:
    level: DEBUG
    category:
      "org.jboss.as.quickstarts.kitchensink":
        level: DEBUG 